Process tree and Content of directory
Artur-Aghajanyan/VSU_ITC pull request #190
Opened 2021-05-20 19:28 UTC by nare99

1. Added 20_05 directory, which contains homework for 20_05
2. Added 1 directory (into 20_05), which contains Process tree homework(ptree.sh and README.md files)
3. Added 2 directory (into 20_05), which contains Content of directory homework( print_dir_content and README.md files)

2021-05-21 08:02 UTC, garik-iskandaryan-im requested changes

2021-05-21 08:02 UTC, garik-iskandaryan-im commented on Nare/BASH/20_05/2/print_dir_content
> +rm helper
need to use functions and print size/files count for nested folders/files as well

2021-05-21 08:48 UTC, nare99 commented on Nare/BASH/20_05/2/print_dir_content
> +rm helper
Added recursion in last commit.

2021-05-23 20:09 UTC, Araksya-Hambaryan approved these changes

2021-05-23 20:10 UTC, merged