Homework for 20 May 2021
Artur-Aghajanyan/VSU_ITC pull request #191
Opened 2021-05-20 19:46 UTC by Gor07s

2021-05-21 08:02 UTC, garik-iskandaryan-im requested changes

2021-05-21 08:02 UTC, garik-iskandaryan-im commented on Gor/20_05_2021/dir.sh
> +directory $1
Need to print size/files count for nested folders/files as well

2021-05-21 08:02 UTC, garik-iskandaryan-im commented on Gor/20_05_2021/process.sh
> +process $1
Getting the following error

`./process.sh: line 11: [: too many arguments
`

2021-05-23 20:11 UTC, Araksya-Hambaryan approved these changes

2021-05-23 20:12 UTC, merged