Done homework
Artur-Aghajanyan/VSU_ITC pull request #193
Opened 2021-05-21 07:00 UTC by Artur-Aghajanyan

I add folder 20_05_2021
into that Folder, there are two .sh files: **child_processes.sh, directoryOrFile.sh**

- Into **child_processes.sh** I made a script that will get name process and will be return child all processes.
- Into directoryOrFile.sh I made a script that will get any name and will return the result it is a file or directory. if will file will be return size that file, if will folder will return how many items are in that directory.

2021-05-21 08:52 UTC, garik-iskandaryan-im requested changes

2021-05-21 08:52 UTC, garik-iskandaryan-im commented on Artur_Aghajanyan/20_05_2021/child_processes.sh
> +	if [ -z $pid]
missing white space before ']'

2021-05-21 08:52 UTC, garik-iskandaryan-im commented on Artur_Aghajanyan/20_05_2021/directoryOrFile.sh
> +findIt $NAME
Works incorrectly, will return information for all nested folders/files

2021-05-23 20:13 UTC, Araksya-Hambaryan approved these changes

2021-05-23 20:15 UTC, merged