Zina/python/25 may2021
Artur-Aghajanyan/VSU_ITC pull request #226
Opened 2021-05-25 21:41 UTC by ZinaYeghiazaryan

Pascal.py file prints out the first n rows of Pascal's triangle. 
Perfect_Number.py file checks whether a number is perfect or not.
Fibonacci.py file prints out the n-th Fibonacci item.

2021-05-26 20:04 UTC, ani-im requested changes

2021-05-26 20:04 UTC, ani-im commented on Zina_Yeghiazaryan/python/25_05_2021/Fibonacci.py
> +        print()
for 0 value 
![image](https://user-images.githubusercontent.com/80816144/119723085-1dcc0a00-be7e-11eb-84c0-c7117e284b27.png)

for 1000
![image](https://user-images.githubusercontent.com/80816144/119723280-553ab680-be7e-11eb-9610-42dcb82aec14.png)
 
 for -2
 
![image](https://user-images.githubusercontent.com/80816144/119723347-65529600-be7e-11eb-9aa9-f3dc4f9046fc.png)

2021-05-26 20:04 UTC, ani-im commented on Zina_Yeghiazaryan/python/25_05_2021/Fibonacci.py
> +        print()
Correct style for function_name, file name based on pep8

2021-05-26 20:04 UTC, ani-im commented on Zina_Yeghiazaryan/python/25_05_2021/Pascal.py
> +        print()
1. why double?
![image](https://user-images.githubusercontent.com/80816144/119723578-a8ad0480-be7e-11eb-8e34-f70bfb68a5b1.png)

2. Fix for big number (e.g 1000000)
![image](https://user-images.githubusercontent.com/80816144/119723704-cb3f1d80-be7e-11eb-85df-4d3fd215c3b9.png)

2021-05-26 20:04 UTC, ani-im commented on Zina_Yeghiazaryan/python/25_05_2021/Pascal.py
> +        print()
again fix styles based on pep8

2021-05-26 20:04 UTC, ani-im commented on Zina_Yeghiazaryan/python/25_05_2021/Perfect_Number.py
> +        print()
Perfect number should be positive number
- https://www.britannica.com/science/perfect-number

Coding style with pep8

2021-05-27 16:09 UTC, ZinaYeghiazaryan commented
https://github.com/Artur-Aghajanyan/VSU_ITC/tree/Zina/python/25May2021/Zina_Yeghiazaryan/python/25_05_2021


On Thu, May 27, 2021 at 12:05 AM ani-im ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In Zina_Yeghiazaryan/python/25_05_2021/Fibonacci.py
> <https://github.com/Artur-Aghajanyan/VSU_ITC/pull/226#discussion_r640080571>
> :
>
> > +        Fib function has one argument, which should be a natural number (n).
> +        The function returns the n-th Fibonacci item.
> +    '''
> +    if n == 0:
> +        return 0
> +    if n == 1:
> +        return 1
> +    return Fib(n - 1) + Fib(n - 2)
> +
> +while True:
> +    try:
> +        n = int(input("Enter the number: "))
> +        print(str(n) + " Fibonacci item is: " + str(Fib(n - 1)))
> +    except ValueError:
> +        print("Entered wrong value. Please enter a number.")
> +        print()
>
> for 0 value
> [image: image]
> <https://user-images.githubusercontent.com/80816144/119723085-1dcc0a00-be7e-11eb-84c0-c7117e284b27.png>
>
> for 1000
> [image: image]
> <https://user-images.githubusercontent.com/80816144/119723280-553ab680-be7e-11eb-9610-42dcb82aec14.png>
>
> for -2
>
> [image: image]
> <https://user-images.githubusercontent.com/80816144/119723347-65529600-be7e-11eb-9aa9-f3dc4f9046fc.png>
> ------------------------------
>
> In Zina_Yeghiazaryan/python/25_05_2021/Pascal.py
> <https://github.com/Artur-Aghajanyan/VSU_ITC/pull/226#discussion_r640082350>
> :
>
> > +        The function prints out the first n rows of Pascal's triangle.
> +    '''
> +    for i in range(0, n+1):
> +        for j in range(0, i+1):
> +            k = Fact(i)/(Fact(j) * Fact(i-j))
> +            print(k, end = ' ')
> +        print("\n")
> +
> +while True:
> +    try:
> +        n = int(input("Enter the number of row: "))
> +        print("First " + str(n) + " rows of Pascal's triangle: ")
> +        Pascal(n)
> +    except ValueError:
> +        print("Entered wrong value. Please enter a number.")
> +        print()
>
>
>    1.
>
>    why double?
>    [image: image]
>    <https://user-images.githubusercontent.com/80816144/119723578-a8ad0480-be7e-11eb-8e34-f70bfb68a5b1.png>
>    2.
>
>    Fix for big number (e.g 1000000)
>    [image: image]
>    <https://user-images.githubusercontent.com/80816144/119723704-cb3f1d80-be7e-11eb-85df-4d3fd215c3b9.png>
>
> ------------------------------
>
> In Zina_Yeghiazaryan/python/25_05_2021/Perfect_Number.py
> <https://github.com/Artur-Aghajanyan/VSU_ITC/pull/226#discussion_r640083669>
> :
>
> > +    '''
> +        Check function has one argument, which should be a natural number.
> +        The function checks if the argumen is perfect.
> +    '''
> +    if (DivSum(n) - n) == 0:
> +        print(str(n) + " is a perfect number.")
> +    else:
> +        print(str(n) + " is not a perfect number.")
> +
> +while True:
> +    try:
> +        n = int(input("Enter the number: "))
> +        Check(n)
> +    except ValueError:
> +        print("Entered wrong value. Please enter a number.")
> +        print()
>
> Perfect number should be positive number
>
>    - https://www.britannica.com/science/perfect-number
>
> Coding style with pep8
> ------------------------------
>
> In Zina_Yeghiazaryan/python/25_05_2021/Fibonacci.py
> <https://github.com/Artur-Aghajanyan/VSU_ITC/pull/226#discussion_r640080984>
> :
>
> > +        Fib function has one argument, which should be a natural number (n).
> +        The function returns the n-th Fibonacci item.
> +    '''
> +    if n == 0:
> +        return 0
> +    if n == 1:
> +        return 1
> +    return Fib(n - 1) + Fib(n - 2)
> +
> +while True:
> +    try:
> +        n = int(input("Enter the number: "))
> +        print(str(n) + " Fibonacci item is: " + str(Fib(n - 1)))
> +    except ValueError:
> +        print("Entered wrong value. Please enter a number.")
> +        print()
>
> Correct style for function_name, file name based on pep8
> ------------------------------
>
> In Zina_Yeghiazaryan/python/25_05_2021/Pascal.py
> <https://github.com/Artur-Aghajanyan/VSU_ITC/pull/226#discussion_r640082472>
> :
>
> > +        The function prints out the first n rows of Pascal's triangle.
> +    '''
> +    for i in range(0, n+1):
> +        for j in range(0, i+1):
> +            k = Fact(i)/(Fact(j) * Fact(i-j))
> +            print(k, end = ' ')
> +        print("\n")
> +
> +while True:
> +    try:
> +        n = int(input("Enter the number of row: "))
> +        print("First " + str(n) + " rows of Pascal's triangle: ")
> +        Pascal(n)
> +    except ValueError:
> +        print("Entered wrong value. Please enter a number.")
> +        print()
>
> again fix styles based on pep8
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Artur-Aghajanyan/VSU_ITC/pull/226#pullrequestreview-669485962>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATBVCBVVIIZJ4QRN37ZYTLDTPVH7FANCNFSM45QIQPHQ>
> .
>

2021-05-27 20:25 UTC, merged