Gor/git/03 mar2021
Artur-Aghajanyan/VSU_ITC pull request #4
Opened 2021-03-03 19:52 UTC by Gor07s

2021-03-03 20:00 UTC, mKolibri requested changes

2021-03-03 20:00 UTC, mKolibri commented on Gor/homework
> +2. git chechout -d branch_name ֊ ջնջում է ․․․ բռենչը լոկալից
Are you sure, that this command delete the branch?

2021-03-03 20:08 UTC, Gor07s commented on Gor/homework
> +2. git chechout -d branch_name ֊ ջնջում է ․․․ բռենչը լոկալից
yes, it is not?

2021-03-03 20:16 UTC, Gor07s commented on Gor/homework
> +2. git chechout -d branch_name ֊ ջնջում է ․․․ բռենչը լոկալից
I edit my file, pliz check it.

2021-03-04 10:39 UTC, mKolibri approved these changes

2021-03-04 10:40 UTC, mKolibri commented
Hi,

I rereviewed your PR. Also marked as Approved. Please chaage PR Ready for
review and delete the branch.

Thanks,
Mane Antonyan

чт, 4 мар. 2021 г. в 00:16, Gor07s <notifications@github.com>:

> *@Gor07s* commented on this pull request.
> ------------------------------
>
> In Gor/homework
> <https://github.com/Artur-Aghajanyan/VSU_ITC/pull/4#discussion_r586747931>
> :
>
> > @@ -0,0 +1,3 @@
>
> +1. git chechout -b branch_name - ստեղծում է նոր բռենչ ․․․ անունով
>
> +2. git chechout -d branch_name ֊ ջնջում է ․․․ բռենչը լոկալից
>
>
> I edit my file, pliz check it.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Artur-Aghajanyan/VSU_ITC/pull/4#discussion_r586747931>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKXTYCDSPHPWQ6YFBK5ZBULTB2KLPANCNFSM4YR32PAA>
> .
>

2021-03-04 13:03 UTC, Gor07s commented
Merge pull request,or whill you?

2021-03-04 15:07 UTC, merged