Nare/c++/19 mar2021
Artur-Aghajanyan/VSU_ITC pull request #69
Opened 2021-03-19 16:42 UTC by nare99

Added homework without templates

2021-03-19 18:07 UTC, mKolibri requested changes
Your codding style not good, but you can be more carefully.
Also please optimize the code, and you need to remember that Git can not diff binary file. It will upload entry file into repository and will store it's pretty much forever. Delete it.

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.cpp
> +    else {
Delete extra 'else'

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.h
> +        int image;
Please implement setters and getters :)

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +    Complex a1, b1;
Declare every new variable in new line

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +    std::cout << "Use of overloaded operator>>" << std::endl << "(Enter 2 complex numbers)" << std::endl;
Note ** Use 2 cout for info, this one is so long :)

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +    std::cout << c <<std::endl;
std::cout << c << std::endl;
You lost 'space'

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +    std::cout << "Count (5+2i)+(3+4i)"<<std::endl;
Note * bad codding style for this line

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +    std::cout << "Count (5+2i)-(3+4i)"<<std::endl;
Note *

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +    std::cout << "Count (5+2i)*(3+4i)"<<std::endl;
Note *

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +    std::cout << "Count entered complex numbers` (" << a1 << ")/(" << b1 << ") division(returns int)" << std::endl;
Note **

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +    std::cout << "Called print function with static variable 4 times"<<std::endl;
Note *

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +    std::cout<<print()<<std::endl;
Note *

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +return 0;
there should be 4 spaces at the beginning of line

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.cpp
> +Complex Complex::operator/(const Complex& a) {
Good work :100:

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.cpp
> +    c.real = ((this -> real * a.real)  + (this -> image * a.image))/((a.real * a.real) + (a.image * a.image));
use variables for this lines, it is so long

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.cpp
> + Overload operator<<
wrong comment :)

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.cpp
> +  Constructor witout paramerts
Do you mean Default constructor ? :)

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.cpp
> +
extra line

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.h
> +         function with static member
Extra comment ? :)

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.h
> +class Complex {
please always write header files with #ifndef, .... #endif

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +int print();
write on header file

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> + int print() {
write in other cpp file !

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/main.cpp
> +     ++count;
Instead of { ++count; return count; }
you can use -> { return count++; }

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.cpp
> +    if(a.real != 0) {
after if must be state.

2021-03-19 18:07 UTC, mKolibri commented on Nare/19_03/complex.cpp
> +            }
Please optimize this function

2021-03-19 18:12 UTC, mKolibri requested changes
Your codding style not good, but you can be more carefully.
Also please optimize the code, and you need to remember that Git can not diff binary file. It will upload entry file into repository and will store it's pretty much forever. Delete it.

2021-03-19 18:12 UTC, mKolibri commented on Nare/19_03/complex.cpp
> +    c.image = ((this -> real * (-a.image))  + (this -> image * a.real))/((a.real * a.real) + (a.image * a.image));
you must check if second part is not 0, or you can have division by 0 exception.

2021-03-20 09:26 UTC, nare99 commented on Nare/19_03/main.cpp
> +    std::cout << "Count entered complex numbers` (" << a1 << ")/(" << b1 << ") division(returns int)" << std::endl;
Can i use 3 cout?`
std::cout << "Count entered complex numbers`"; 
std::cout << "(" << a1 << ")/(" << b1 << ")"; 
std::cout << "division(returns int)" << std::endl;

2021-03-20 09:48 UTC, nare99 commented on Nare/19_03/complex.cpp
> +  Constructor witout paramerts
Yes.

2021-03-20 09:50 UTC, nare99 commented on Nare/19_03/complex.h
> +         function with static member
Print function first was written as class method, then I forget to delete comment.

2021-03-20 10:25 UTC, nare99 commented on Nare/19_03/main.cpp
> +     ++count;
return count++ returns count's previous value. I will write ++count to get real count of function calls

2021-04-06 16:35 UTC, merged